A = float(input("Введите координату точки A: "))
B = float(input("Введите координату точки B: "))
C = float(input("Введите координату точки C: "))
AC = abs(C - A)
BC = abs(C - B)
sum_AC_BC = AC + BC
print(f"Длина отрезка AC = {AC}")
print(f"Длина отрезка BC = {BC}")
print(f"Сумма длин = {sum_AC_BC}")
